"""Remove review fields from DirectorReview

Revision ID: 6190644499e6
Revises: 8d2a3d906178
Create Date: 2025-09-17 08:48:57.295136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6190644499e6'
down_revision = '8d2a3d906178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('director_review', schema=None) as batch_op:
        batch_op.drop_column('audiometry_review')
        batch_op.drop_column('spirometry_review')
        batch_op.drop_column('ecg_review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('director_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecg_review', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('spirometry_review', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('audiometry_review', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
