"""Enhance DirectorReview model with new fields

Revision ID: 8d2a3d906178
Revises: 062e3bf9a677
Create Date: 2025-09-17 06:48:51.986242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2a3d906178'
down_revision = '062e3bf9a677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('director_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spirometry_review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audiometry_review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ecg_review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_one', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_two', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_three', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment_four', sa.Text(), nullable=True))
        batch_op.alter_column('director_remarks',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('overall_assessment',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('director_review', schema=None) as batch_op:
        batch_op.alter_column('overall_assessment',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('director_remarks',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('comment_four')
        batch_op.drop_column('comment_three')
        batch_op.drop_column('comment_two')
        batch_op.drop_column('comment_one')
        batch_op.drop_column('ecg_review')
        batch_op.drop_column('audiometry_review')
        batch_op.drop_column('spirometry_review')

    # ### end Alembic commands ###
