"""Add username to User model and make email required

Revision ID: 93897f2e97a8
Revises: 6190644499e6
Create Date: 2025-09-19 18:01:07.440583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93897f2e97a8'
down_revision = '6190644499e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=True))
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    op.execute("UPDATE user SET username = 'temp' || id, email_address = 'temp' || id || '@example.com' WHERE username IS NULL OR email_address IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.alter_column('email_address', nullable=False)
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
