"""Add Consultation model

Revision ID: bd981e93f380
Revises: 9bd09a43e81b
Create Date: 2025-09-12 14:59:05.560322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd981e93f380'
down_revision = '9bd09a43e81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('luts', sa.String(length=50), nullable=True),
    sa.Column('chronic_cough', sa.String(length=50), nullable=True),
    sa.Column('chronic_chest_pain', sa.String(length=50), nullable=True),
    sa.Column('chest_infection', sa.String(length=50), nullable=True),
    sa.Column('heart_dx', sa.String(length=50), nullable=True),
    sa.Column('palor', sa.String(length=50), nullable=True),
    sa.Column('jaundice', sa.String(length=50), nullable=True),
    sa.Column('murmur', sa.String(length=50), nullable=True),
    sa.Column('chest', sa.String(length=50), nullable=True),
    sa.Column('psa', sa.String(length=50), nullable=True),
    sa.Column('psa_remark', sa.Text(), nullable=True),
    sa.Column('fbs', sa.String(length=50), nullable=True),
    sa.Column('rbs', sa.String(length=50), nullable=True),
    sa.Column('fbs_rbs_remark', sa.String(length=50), nullable=True),
    sa.Column('urine_analysis', sa.String(length=100), nullable=True),
    sa.Column('ua_remark', sa.String(length=50), nullable=True),
    sa.Column('diabetes_mellitus', sa.String(length=100), nullable=True),
    sa.Column('hypertension', sa.String(length=100), nullable=True),
    sa.Column('bp', sa.String(length=50), nullable=True),
    sa.Column('pulse', sa.String(length=50), nullable=True),
    sa.Column('spo2', sa.String(length=50), nullable=True),
    sa.Column('hs_1_and_2', sa.String(length=50), nullable=True),
    sa.Column('breast_exam', sa.String(length=50), nullable=True),
    sa.Column('breast_exam_remark', sa.Text(), nullable=True),
    sa.Column('abdomen', sa.String(length=50), nullable=True),
    sa.Column('assessment_hx_pe', sa.String(length=100), nullable=True),
    sa.Column('other_assessments', sa.Text(), nullable=True),
    sa.Column('overall_lab_remark', sa.Text(), nullable=True),
    sa.Column('other_remarks', sa.Text(), nullable=True),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation')
    # ### end Alembic commands ###
