"""Add email_address to User model

Revision ID: d09157323422
Revises: 91dd3c35e0af
Create Date: 2025-09-13 12:46:48.820196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09157323422'
down_revision = '91dd3c35e0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint("uq_user_email_address", ['email_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email_address", type_='unique')
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
